services:
  db:
    # image: mysql:8.0
    build: .
    container_name: turma-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mel2020gor
      MYSQL_DATABASE: aula_db
    ports:
      - "3306:3306"
    volumes:
      - meus-dados-mysql:/var/lib/mysql
      
volumes:
  meus-dados-mysql: